### ISSUE TITLE
Libsyn provided JSON feed

### ISSUE THREAD

**Issue by MylesJohnson** [nitricware/VGOgrabber#4]
LibSyn provides an (undocumented) JSON feed that you may want to parse rather than the HTML directly.

`https://html5-player.libsyn.com/embed/list/id/58049/size/25/sort_by_field/release_date/sort_by_direction/desc`

**Comment by nitricware** [comment]
That's awesome!!! Thanks for sharing!

I'll have a look at it. This is of course way more reliable than the xpath shenanigans!
